variables:
  - group: Presidio-V2-CI

stages:
  - stage: DeployDev
    variables:
      REGISTRY_NAME: '$(ACR_REGISTRY_NAME).azurecr.io/'
    displayName: Deploy to Dev environment
    jobs:
      - job: TestDeployment
        displayName: Smoke and E2E Tests on the deployement
        variables:
          ANALYZER_STAGING_URI: 'https://presidio-analyzer-dev-staging.azurewebsites.net'
          ANONYMIZER_STAGING_URI: 'https://presidio-anonymizer-dev-staging.azurewebsites.net'
        steps:
          - task: Bash@3
            displayName: 'Wait and Smoke test'
            timeoutInMinutes: 10
            inputs:
              targetType: 'inline'
              script: |
                set -ux  # do not fail on error

                ANALYZER_STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 --max-time 10 $ANALYZER_STAGING_URI/health)
                ANONYMIZER_STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 --max-time 10 $ANONYMIZER_STAGING_URI/health)
                echo analyzer status code is $ANALYZER_STATUS_CODE
                echo anonymizer status code is $ANONYMIZER_STATUS_CODE

                while [ ! $ANALYZER_STATUS_CODE == 200 ] || [ ! $ANONYMIZER_STATUS_CODE == 200 ]
                do
                    sleep 30
                    ANALYZER_STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 --max-time 10 $ANALYZER_STAGING_URI/health)
                    ANONYMIZER_STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 1 --max-time 10 $ANONYMIZER_STAGING_URI/health)
                    echo analyzer status code is $ANALYZER_STATUS_CODE
                    echo anonymizer status code is $ANONYMIZER_STATUS_CODE
                done
          - template: .pipelines/templates/e2e-tests.yml
            parameters:
              test_suite: 'integration'
              analyzer_base_url: 'https://presidio-analyzer-dev-staging.azurewebsites.net'
              anonymizer_base_url: 'https://presidio-anonymizer-dev-staging.azurewebsites.net'

